config/routes.rb
Rails.application.routes.draw do
  resources :jobs do
    member do
      put :publish
      put :unpublish
      put :apply
      patch :remove_attachment
    end
  end

  root to: "pages#home"
  get "/search", to: "jobs#search"
  get "/hello", to: "pages#hello"
  get "/goodbye", to: "pages#goodbye"
  devise_for :members, controllers: { omniauth_callbacks: "members/omniauth_callbacks", registrations: "members/registrations" }
  resources :members do
    collection do
      get :edit
      get :edit_password
      patch :update_password
      patch :delete_profile_photo
    end
  end
end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id                   :bigint           not null, primary key
#  company_name         :string
#  description          :text
#  featured             :boolean          default(FALSE)
#  listing_expires      :datetime
#  pay_interval         :string
#  payment              :string
#  payment_details      :text
#  published            :boolean          default(FALSE)
#  shoot_end_date       :datetime
#  shoot_location       :string
#  shoot_start_date     :datetime
#  special_instructions :text
#  title                :string
#  union_status         :string
#  url                  :string
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  member_id            :bigint           not null
#
# Indexes
#
#  index_jobs_on_member_id  (member_id)
#
# Foreign Keys
#
#  fk_rails_...  (member_id => members.id)
#
class Job < ApplicationRecord

  # ASSOCIATIONS
  # ======================================================================
  belongs_to :member
  has_many :roles, dependent: :destroy
  accepts_nested_attributes_for :roles, allow_destroy: true, reject_if: :all_blank
  has_one_attached :production_image
  # has_rich_text :description

  # VALIDATIONS
  # ======================================================================
  validate :acceptable_image
  validates :title, presence: true
  validates :description, presence: true
  validates :shoot_location, presence: true

  # SCOPES
  # ======================================================================
  scope :featured, -> { where(featured: true).order(created_at: :desc) }
  scope :published, -> { where(published: true).order(created_at: :desc) }

  # CONSTANTSS
  # ======================================================================
  UNION_STATUS = ["Any", "SAG", "SAG-AFTRA", "Nonunion"]
  PAY_INTERVAL = ["Hour", "Day", "Week", "Month", "Project", "8 Hours"]
  LOCATION = ["Albuquerque", "Santa Fe", "Taos", "Las Vegas", "Espanola"]

  # HELPERS
  # ======================================================================
  def acceptable_image
    return unless production_image.attached?
    errors.add(:production_image, "is nil") if production_image.attached?.nil?
    errors.add(:production_image, "is too big") unless production_image.byte_size <= 3.megabyte
    acceptable_types = ["image/jpeg", "image/png"]
    errors.add(:production_image, "must be JPEG or PNG") unless acceptable_types.include?(production_image.content_type)
  end

  def some_image # display some_image if attached blob is nil
    "https://dummyimage.com/800x600/f0f0f0/d4d4d4"
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :fetch_job, only: [:publish, :unpublish, :apply, :show, :edit, :update, :destroy]
  before_action :authenticate_member!, except: %i[index show search]
  load_and_authorize_resource #cancancan authorizationn

  def index
    @jobs = Job.published.all.limit(9)
  end

  def show
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @job = Job.new
  end

  def edit
  end

  def create
    @job = Job.new(job_params)
    @job.member = current_member

    respond_to do |format|
      if @job.save
        # @job.production_image.attach(params[:signed_blob_id])
        format.html { redirect_to @job, notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to member_url(current_member), notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def apply
    @job = Job.find(params[:id])
    @talent = current_member
    respond_to :html
    JobMailer.with(talent: @talent, job: @job).apply_email.deliver_now
  end

  def search
    if params[:search].blank?
      redirect_to(jobs_path, notice: "Nothing to search") and return
    else
      @parameter = params[:search].downcase
      @results = Job.all.where("title ILIKE :search OR description ILIKE :search", search: "%#{@parameter}%")
    end
  end

  def publish
    respond_to do |format|
      if @job.update(published: true)
        format.js { redirect_to @job, notice: "This job is now published!" }
        # format.html { redirect_to @job, notice: "This job is now published!" }
        # format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def unpublish
    respond_to do |format|
      if @job.update(published: false)
        format.js { redirect_to @job, notice: "Job unpublished" }
        #format.html { redirect_to @job, notice: "Job unpublished" }
        #format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def remove_attachment
    @job = Job.find(params[:id])
    #@job.production_image.purge
    respond_to do |format|
      if @job.update(production_image: nil)
        format.js { }
        # format.html { render :edit, notice: "Image removed" }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def fetch_job
    @job = Job.find(params.require(:id))
  end

  # Only allow a list of trusted parameters through.
  def job_params
    params.require(:job).permit(
      :title,
      :description,
      :company_name,
      :listing_expires,
      :url,
      :union_status,
      :payment,
      :payment_details,
      :shoot_start_date,
      :shoot_end_date,
      :shoot_location,
      :special_instructions,
      :member_id,
      :production_image,
      :pay_interval,
      roles_attributes: [:id, :role_name, :role_description, :_destroy],
    )
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
  #Change color of Job status.
  def published?(job)
    if job.published?
      @class = "success"
      @status = "Published"
    else
      @class = "primary"
      @status = "Pending"
    end
  end
end

app/views/jobs/_form.html.erb
<%= form_with(model: @job, local: true, multipart: true, id:'create-job-form') do |f| %>
<%= render "form_errors", object: @job %>

  <div class="bg-light rounded shadow-sm p-5">
    <div class="form-group input-group-lg">
      <%= f.label "Casting title" %>
      <%= f.text_field :title, class:'form-control', placeholder:"eg: Men with long beards" %>
    </div>
  
    <div class="form-group input-group-lg">
      <%= f.label :description %>
      <%# f.rich_text_area :description, class: 'form-control' %>
      <%= f.text_area :description, rows: 8, class: 'form-control' %>
    </div>
  </div>

  <h4 class="mt-5 mb-4">Add Image <small>(optional)</small></h4>

  <div class="bg-light rounded shadow-sm p-5">
    <div class="form-group input-group-lg">
      <%= f.label :production_image %>
      <% unless @job.production_image.attached? %>
        <div class="bg-light rounded dropzone dropzone-default dz-clickable " data-controller="dropzone" data-dropzone-max-file-size="2" data-dropzone-max-files="1">
          <%= f.file_field :production_image, direct_upload: true, data: { target: 'dropzone.input' } %>
          <div class="dropzone-msg dz-message needsclick ">
            <p class="dropzone-msg-title">Drag image here to start upload or tap to browse</p>
            <span class="dropzone-msg-desc small text-muted">2 MB file size maximum. Allowed file types png, jpg.</span>
          </div>
        </div>
      <% else %>
        <div class="job-image">
        <%= image_tag(@job.production_image.variant(resize_to_limit: [800,800]),class:"img-fluid w-100 rounded") %>
        <%= link_to('Remove Photo', remove_attachment_job_path, method: :patch, remote: true, class:"") %>
        </div>
      <% end %>
    </div>
  </div>

  <h4 class="mt-5 mb-4">Roles</h4>

  <div class="bg-light rounded shadow-sm p-5">
    <div data-controller="nested-form">
      <template data-target='nested-form.template'>
        <%= f.fields_for :roles, Role.new, child_index: 'TEMPLATE_RECORD' do |role| %>
          <%= render 'role_fields', f: role %>
        <% end %>
      </template>
  
      <%= f.fields_for :roles do |role| %>
        <%= render 'role_fields', f: role %>
      <% end %>
  
      <div data-target="nested-form.add_item">
        <%= link_to "Add Role", "#", data: { action: "nested-form#add_association" } %>
      </div>
    </div>
  </div>



  <h4 class="mt-5 mb-4">Dates and Location</h4>

  <div class="bg-light rounded shadow-sm p-5">
    <div class="form-row">
      <div class="col-lg-6">
        <div class="form-group mb-3">
          <div class="input-group input-group-lg">
                <div class="input-group-prepend ">
                <span class="input-group-text bg-light">Start</span>
              </div>
            <%= f.text_field :shoot_start_date, class:'form-control flatpickr-input', data: {behavior: 'flatpickr'}, placeholder: "Date Select" %>
          </div>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="form-group mb-3">
          <div class="input-group input-group-lg">
            <div class="input-group-prepend">
              <span class="input-group-text bg-light">End</span>
            </div>
            <%= f.text_field :shoot_end_date, class:'form-control flatpickr-input', data: {behavior: 'flatpickr'}, placeholder: "Date Select" %>
          </div>
        </div>
      </div>
    </div>
  
    <div class="form-group input-group-lg">
      <%= f.label "Location" %>
      <%= f.select :shoot_location, Job::LOCATION,{ include_blank: false }, class: 'form-control custom-select' %>
    </div>
  </div>

  <h4 class="mt-5 mb-4">Payment</h4>

  <div class="bg-light rounded shadow-sm p-5">
    <div class="form-row">
      <div class="col-lg-7">
        <div class="input-group input-group-lg mb-3">
          <div class="input-group-prepend ">
            <span class="input-group-text bg-light">$</span>
          </div>
          <%= f.text_field :payment, class: 'form-control col-5', placeholder:"" %>
          <div class="input-group-prepend input-group-append">
            <span class="input-group-text bg-light">/</span>
          </div>
          <%= f.select :pay_interval, Job::PAY_INTERVAL,{ include_blank: false }, class: 'form-control custom-select col-5' %>
        </div>
      </div>
      <div class="col">
        <div class="form-group input-group-lg">
          <%= f.select :union_status, Job::UNION_STATUS,{ include_blank: "Union status" }, class: 'form-control custom-select' %>
        </div>
      </div>
    </div>
    <div class="form-group input-group-lg">
      <%= f.label :payment_details %>
      <%= f.text_area :payment_details, rows: 5, class: 'form-control' %>
    </div>
  </div>

  <h4 class="mt-5 mb-4">Production Details</h4>
  
  <div class="bg-light rounded shadow-sm p-5">
    <div class="form-group input-group-lg">
      <%= f.label "Production name" %>
      <%= f.text_field :company_name, class: 'form-control' %>
    </div>
  
    <div class="form-group input-group-lg">
      <%= f.label 'Production URL' %>
      <%= f.url_field :url, class: 'form-control' %>
    </div>
  </div>

  <h4 class="mt-5 mb-4">Submissions</h4>

  <div class="bg-light rounded shadow-sm p-5">
    <div class="form-group input-group-lg">
    <%= f.label 'Any pecial instructionns or requirements for submitting?' %>
      <%= f.text_area :special_instructions, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group input-group-lg">
    <%# f.label :listing_expires %>
    <%# f.text_field :listing_expires, data: {behavior: 'flatpickr'}, class: 'form-control flatpickr-input', placeholder:"Set date when this listing should be removed." %>
  </div>

  <div class="form-group input-group-lg">
    <div class="actions">
      <%= f.submit class: 'btn btn-success btn-lg' %>
    </div>
  </div>
<% end %>

app/views/jobs/_form_errors.html.erb
  <% if object.errors.any? %>
    <div id="error_explanation" class="alert alert-danger bg-action">
      <h4>Hey check the form</h4>
      <ul>
        <% object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/jobs/_full_job.html.erb
<%# This template is for home page only  %>
<div class="mx-auto pb-3" style="max-width: 600px;" >
  <div class="sticky-top bg-light">
    <h3 class=""><%= @job.title %></h1>
    <p><%= @job.description %></p>
    <p><%= @job.union_status %> <strong>$ <%= @job.payment %></strong></p>
    <% if can? :apply, @job || member_signed_in? %>
      <%= link_to 'Apply Now', apply_job_path(@job), method: :put, class:'btn btn-success' %>
    <% else %>
      <%= link_to 'Log in to Apply', new_member_session_path, class:'btn btn-action' %>
    <% end %>
    <%= link_to('#', class: "float-right mx-2", title:'Save', :data => { :'toggle' => 'tooltip' }) do %>
      <%= icon("bookmark", class: "text-info align-middle") %>
    <% end %>
    <%= link_to(job_path(@job),class: "float-right mx-2", title:'Show', :data => { :'toggle' => 'tooltip' }) do %>
      <%= icon("box-arrow-up-right", class: "text-info align-middle") %>
    <% end %>
    <hr>
  </div>
  <p> <span>Dates & Location:</span><br>
    <%= @job.shoot_start_date %> - <%= @job.shoot_end_date %> in <%= @job.shoot_location %></p>
  <p><%= @job.url %></p>
  <p><%= @job.payment_details %></p>
  <%= image_tag(@job.production_image, class:'img-fluid w-100') if @job.production_image.attached? %>
</div>

app/views/jobs/_job.html.erb
<div class="card shadow-sm mb-3">
  <div class="card-body">
  <h4 class="card-title">
    <% unless job.created_at < DateTime.current.days_ago(5) %>
      <span class="badge bg-action small text-dark mr-2">New</span>
    <% end %>
    <%= link_to job.title, job_path(job), remote: false, class:'text-reset', id:'remote' %>
    </h4>
    <p class="card-text small"><span class="text-muted">Posted by:</span> <%= link_to(job.member.first_name,member_path(job.member_id)) %> <span class="  text-muted">  <%= time_ago_in_words(job.created_at) %> ago</span></p>
    <p class="text-muted small mb-0">Union Status: <%= job.union_status %></p>
    <p class="text-muted small">Shoots: <%= job.shoot_start_date %> - <%= job.shoot_end_date %> in <%= job.shoot_location %></p>
    <p class="card-text font-weight-light"><%= truncate(job.description, :ommision => "... Read More", :length => 150) %></p>
    <p class="card-text font-weight-bold">$<%= job.payment %></p>
    <p class="card-text">
      <%# link_to "View Details", job_path(job), class: "link-stretch" %>
    </p>
  </div>
  <%# if job.production_image.attached? %>
    <%# image_tag(job.production_image, class:"card-img clear", :alt => "...") %>
    <%# else %>
    <%# image_tag(job.some_image, class:"card-img clear", :alt => "...") %>
  <%# end %>
</div>

app/views/jobs/_job_card.html.erb
<%# This job template is for home page only %>
<% @jobs.each do |job| %>
  <div class="card shadow-sm mb-3">
    <div class="card-body" style="transform: rotate(0);">
    <h6 class="card-title">
      <% unless job.created_at < DateTime.current.days_ago(5) %>
        <span class="badge bg-action small text-dark mr-2">New</span>
      <% end %>
      <%= link_to job.title, job_path(job), remote: true, class:'text-reset stretched-link', id:'remote' %>
      </h6>
    <p class="card-text small"><span class="text-muted">Posted by:</span> <%= link_to(job.member.first_name,member_path(job.member_id)) %> <span class="  text-muted">  <%= time_ago_in_words(job.created_at) %> ago</span></p>
      <p class="font-weight-bold"><span class="text-muted small"></span> $<%= job.payment %>/<%= job.pay_interval %></p>
      <p class="text-muted small mb-0">Union Status: <%= job.union_status %></p>
      <p class="text-muted small mb-1">Shoots: <%= job.shoot_start_date %> - <%= job.shoot_end_date %> in <%= job.shoot_location %></p>
    </div>
    <div class="card-body d-sm-none" style="transform: rotate(0);">
      <%= link_to('Details', job_path(job),class:'btn btn-primary stretched-link btn-lg ') %>
    </div>
    <%# if job.production_image.attached? %>
      <%# image_tag(job.production_image, class:"card-img clear", :alt => "...") %>
      <%# else %>
      <%# image_tag(job.some_image, class:"card-img clear", :alt => "...") %>
    <%# end %>
    </div>
<% end %>

app/views/jobs/_job_preview.html.erb
<%= form_with(model: @job, local: true, multipart: true, id:'create-job-form') do |f| %>
<%= render "form_errors", object: @job %>


    <%= @job.title %>
    <%= @job.description %>


  <div class="form-group input-group-lg">
    <%= f.label :production_image %>
    <% unless @job.production_image.attached? %>
      <div class="bg-light rounded dropzone dropzone-default dz-clickable " data-controller="dropzone" data-dropzone-max-file-size="2" data-dropzone-max-files="1">
        <%= f.file_field :production_image, direct_upload: true, data: { target: 'dropzone.input' } %>
        <div class="dropzone-msg dz-message needsclick ">
          <p class="dropzone-msg-title">Drag image here to start upload or tap to browse</p>
          <span class="dropzone-msg-desc small text-muted">2 MB file size maximum. Allowed file types png, jpg.</span>
        </div>
      </div>
    <% else %>
      <div class="job-image">
      <%= image_tag(@job.production_image.variant(resize_to_limit: [800,800]),class:"img-fluid w-100 rounded") %>
      </div>
    <% end %>
  </div>

  <h3 class="mt-5 mb-4">Roles</h3>
  
  <%= f.fields_for :roles do |r| %>
    <div class="form-group input-group-lg">
      <%= r.text_field :role_name , class: 'form-control',placeholder:'Role' %>
    </div>
    <div class="form-group input-group-lg">
      <%= r.text_area :role_description, rows: 4, class: 'form-control', placeholder:'Role description'%>
    </div>
  <% end %>

  <h3 class="mt-5 mb-4">Dates and Location</h3>

  <div class="form-row">
    <div class="col-lg-6">
      <div class="form-group mb-3">
        <div class="input-group input-group-lg">
              <div class="input-group-prepend ">
              <span class="input-group-text bg-light">Start</span>
            </div>
          <%= f.text_field :shoot_start_date, class:'form-control flatpickr-input', data: {behavior: 'flatpickr'}, placeholder: "Date Select" %>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="form-group mb-3">
        <div class="input-group input-group-lg">
          <div class="input-group-prepend">
            <span class="input-group-text bg-light">End</span>
          </div>
          <%= f.text_field :shoot_end_date, class:'form-control flatpickr-input', data: {behavior: 'flatpickr'}, placeholder: "Date Select" %>
        </div>
      </div>
    </div>
  </div>

  <div class="form-group input-group-lg">
    <%= f.label "Location" %>
    <%= f.select :shoot_location, Job::LOCATION,{ include_blank: false }, class: 'form-control custom-select' %>
  </div>

  <h3 class="mt-5 mb-4">Payment</h3>

  <div class="form-row">
    <div class="col">
      <div class="form-group input-group-lg">
        <%= f.select :union_status, Job::UNION_STATUS,{ include_blank: "Union status" }, class: 'form-control custom-select' %>
      </div>
    </div>
  
    <div class="col-lg-5">
      <div class="input-group input-group-lg mb-3">
        <div class="input-group-prepend ">
          <span class="input-group-text bg-light">$</span>
        </div>
        <%= f.text_field :payment, class: 'form-control', placeholder:"" %>
        <div class="input-group-prepend input-group-append">
          <span class="input-group-text bg-light">/</span>
        </div>
        <%= f.select :pay_interval, Job::PAY_INTERVAL,{ include_blank: false }, class: 'form-control custom-select' %>
      </div>
    </div>
  </div>
      

  <div class="form-group input-group-lg">
    <%= f.label :payment_details %>
    <%= f.text_area :payment_details, rows: 5, class: 'form-control' %>
  </div>

  <h3 class="mt-5 mb-4">Production Details</h3>
  
  <div class="form-group input-group-lg">
    <%= f.label "Production name" %>
    <%= f.text_field :company_name, class: 'form-control' %>
  </div>

  <div class="form-group input-group-lg">
    <%= f.label 'Production URL' %>
    <%= f.url_field :url, class: 'form-control' %>
  </div>

  <h3 class="mt-5 mb-4">Submissions</h3>

  <div class="form-group input-group-lg">
    <%= f.text_area :special_instructions, class: 'form-control', placeholder:"Special instructionns or requirements for submitting" %>
  </div>

  <hr class="bg-light">

  <div class="form-group input-group-lg">
    <%= f.label :listing_expires %>
    <%= f.text_field :listing_expires, data: {behavior: 'flatpickr'}, class: 'form-control flatpickr-input', placeholder:"Set date when this listing should be removed." %>
  </div>

  <div class="form-group input-group-lg">
    <div class="actions">
    <%= button_tag 'Preview', name: 'preview_button', class: 'btn btn-primary btn-lg' %>
      <%= f.submit class: 'btn btn-success btn-lg' %>
    </div>
  </div>
<% end %>

app/views/jobs/_role_fields.html.erb
    <div class='nested-fields rounded  mb-3 '>
      <div class="form-group input-group-lg m-0">
        <%= f.hidden_field :_destroy %>
      </div>
      <div class="form-group input-group-lg">
        <%= f.text_field :role_name , class: 'form-control',placeholder:'Role' %>
      </div>
      <div class="form-group input-group-lg">
        <%= f.text_area :role_description, rows: 4, class: 'form-control', placeholder:'Role description'%>
      </div>
      <%= link_to "Remove", "#", data: { action: "click->nested-form#remove_association" }%>
  </div>

app/views/jobs/edit.html.erb
<div class="container">
  <h3 class="mb-5">Edit Casting Call</h3>
  <p class=""><%# icon("chevron-left", class: "text-info align-middle") %><%= link_to 'Back', :back %></p>
  <div class="row justify-content-center">
    <div class="col">
      <div class="">
        <%= render 'form', job: @job %>
      </div>
    </div>

    <% if author_of(@job) || admin? %>
      <div class="col-md-4 pr-md-0 d-none d-md-block">
        <div class="card rounded shadow-sm p-3">
          <p class="small">Created on: <%= @job.created_at%></p>
            <% published?(@job) %><p>Status: <span id='status', class='text-<%=@class%>'><%= @status %></span></p>
            
            <div class="d-inline">
              <div class="btn-group mb-4">
                <% if !@job.published? %>
                
                  <%= link_to('Publish', publish_job_path(@job), remote: true, method: :put, class:"btn btn-sm btn-outline-secondary") %>
                  <%= link_to 'View', @job, class:"btn btn-sm btn-outline-secondary" %>
                <% else %>
                <%= link_to('Unpublish', unpublish_job_path(@job), remote: true, method: :put, class:"btn btn-sm btn-outline-secondary") %>
                <%= link_to 'Delete', job_path(@job), class:"btn btn-sm btn-outline-secondary", method: :delete, data: { confirm: "Are you sure?" }  %>
                <% end %>
              </div>
            </div>
        </div>

          <ul class="list-group list-group-flush mt-3">
            <li class="list-group-item bg-light"><a href="#">Basic Info</a></li>
            <li class="list-group-item bg-light"><a href="#">Image</a></li>
            <li class="list-group-item bg-light"><a href="#">Roles</a></li>
            <li class="list-group-item bg-light"><a href="#">Dates and Locationn</a></li>
            <li class="list-group-item bg-light"><a href="#">Payment</a></li>
            <li class="list-group-item bg-light"><a href="#">Production Details</a></li>
            <li class="list-group-item bg-light"><a href="#">Submitions</a></li>
          </ul>


      </div>
    <% end %>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col">
      <div class="bg-light shadow-sm rounded p-5">
        <div class="border-bottom mb-3 bg-light pb-4">
          <h3 class=""><%= @job.title %></h1>
          <p><%= @job.description %></p>
          <% if @job.roles.present? %>
            <h3>Roles</h3>
            <% @job.roles.each do |job| %>
              <p><%= job.role_name %></p>
              <p><%= job.role_description %></p>
            <% end %>
          <% end %>
          <p><span class="text-secondary">Payment: </span>  $<%= @job.payment %>/<%= @job.pay_interval %><br>
            <%= @job.payment_details %></p>
          <% if can? :apply, @job || member_signed_in? %>
            <%= link_to 'Apply Now', apply_job_path(@job), method: :put, class:'btn btn-success' %>
          <% else %>
            <%= link_to 'Log in to Apply', new_member_session_path, class:'btn btn-action' %>
          <% end %>
        </div>
        <p><span class="text-secondary">Union Status: </span><%= @job.union_status %></p>
        <p><span class="text-secondary">Shoot dates & Location:</span><br>
          <%= @job.shoot_start_date %> - <%= @job.shoot_end_date %> in <%= @job.shoot_location %></p>
        <hr>
        <p><span class="text-secondary">Special Instructions:</span><br>
          <%= @job.special_instructions %></p>
        <%= image_tag(@job.production_image.variant(resize_to_limit: [2000,2000]),class:"img-fluid w-100 rounded") if @job.production_image.attached? %>
        <%# link_to('Remove Photo', remove_attachment_job_path, method: :patch, remote: true, class:"") if @job.production_image.attached? %>
        <% if @job.company_name.present? %>
          <p><span class="text-secondary">Production Details:</span><br>
            <%= @job.company_name %><br>
            <%= @job.url %></p>
        <% end %>
        <p class="card-text small"><span class="text-muted">Posted by:</span> <%= link_to(@job.member.first_name,member_path(@job.member_id)) %> <span class="  text-muted">  <%= time_ago_in_words(@job.created_at) %> ago</span></p>
        <span class= "text-muted small">Listing expires: <%= @job.listing_expires %></span></p>
    </div>
  </div>
  <div class="col-md-4 pr-md-0 d-none d-md-block">
    <div class="card rounded shadow-sm p-3 ">
      <% if can? :manage, @job %>
        <h4 class="mb-5">Manage Listing</h4>
        <p class="small">Created on: <%= @job.created_at%></p>
        <% published?(@job) %>
        <p>Status: <span id='status', class='text-<%=@class%>'><%= @status %></span></p>
        <div class="d-inline">
          <div class="btn-group mb-4">
            <% if !@job.published? %>
              <%= link_to('Publish', publish_job_path(@job), remote: true, method: :put, class:"btn btn-sm btn-outline-secondary") %>
            <% else %>
              <%= link_to('Unpublish', unpublish_job_path(@job), remote: true, method: :put, class:"btn btn-sm btn-outline-secondary") %>
            <% end %>
            <div class="btn-group" role="group" aria-label="Basic outlined example">
              <%= link_to('Edit', edit_job_path(@job),class:"btn btn-sm btn-outline-secondary" )%>
              <%= link_to 'Delete', job_path(@job), class:"btn btn-sm btn-outline-secondary", method: :delete, data: { confirm: "Are you sure?" }  %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>