config/routes.rb
Rails.application.routes.draw do
  resources :jobs do
    member do
      put :publish
      put :unpublish
      put :apply
      patch :remove_attachment
    end
  end

  root to: "pages#home"
  get "/search", to: "jobs#search"
  get "/hello", to: "pages#hello"
  get "/goodbye", to: "pages#goodbye"
  devise_for :members, controllers: { omniauth_callbacks: "members/omniauth_callbacks", registrations: "members/registrations" }
  resources :members do
    collection do
      get :edit
      get :edit_password
      patch :update_password
      patch :delete_profile_photo
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="bg-gray-800 border-top border-gray-800">
  <div class="container">
    <div class="row">
<div class="col">
</div>
    </div>
  </div>
</footer>

app/views/layouts/_jobs_grid.erb
  <% @jobs.each do |job| %> 
    <div class="col-md-6 col-sm-auto col-lg-4 d-flex">
        <div class="card-group">
          <div class="card mb-3 bg-dark" >
            <%= image_tag(job.production_image, class:"card-img-top", :alt => "...") if job.production_image.attached? %>
            <div class="card-img-overlay bg-filter">
              <h5 class="card-title"><%= job.title %></h5>
              <p class="card-text"><%= (job.description) %></p>
              <p class="card-text">
              <%= link_to "View Details", job_path(job), class: "btn btn-info btn-sm" %>
              </p>
              <p class="card-text">
                <span class="small">
                  <%= link_to "Show", job_path(job) %> |
                  <%= link_to "Edit", edit_job_path(job) %> |
                  <%= link_to "Delete", job_path(job), method: :delete, data: { confirm: "Are you sure?" } %>
                </span>
              </p>
            </div>
        </div>
      </div>
    </div>
  <% end %>

app/views/layouts/_modal.html.erb
<div id="crop-modal" class="modal" tabindex="-1" data-backdrop="static" data-controller='avatar'>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Crop Image</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="image-container"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary crop-btn">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar sticky-top navbar-expand-md border-bottom shadow-sm" id="main-nav">
    <%= link_to "Castr", root_path, :class => "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse font-weight-light" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item">
          <%= link_to "Casing Calls", jobs_path, :class => "nav-link text-reset" %>
          <%# link_to "Members", members_path, :class => "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Post a Casting Call", new_job_path, :class => "nav-link text-reset" %>
        </li>
      </ul>
      <div class="custom-control custom-switch mr-5 my-3 my-sm-0">
        <input type="checkbox" class="custom-control-input" id="darkSwitch" />
        <label class="custom-control-label" for="darkSwitch">Dark Mode</label>
      </div>
      <%= render "layouts/usernav" %>
    </div>
</nav>

app/views/layouts/_profile_header.html.erb
<div class="container-fluid bg-light py-5">
  <div class="row justify-content-center">
    <div class="mx-auto text-center" style="width: 200px;">
      <% if @member.avatar  %>
        <%= image_tag(@member.avatar ,class:"img-fluid border border-3 border-info rounded-circle", id:"avatar") %>
      <% else %>
        <%= icon("person-circle",  width: 150, height: 150, class: "text-info align-middle", id:"avatar" ) %>
      <% end %>
      <div class="avatar" data-controller="avatar" >
        <label class="label" data-toggle="tooltip" title="Change your avatar" style="cursor:pointer;">
          <%# render partial: 'members/avatar' %>
          <% if signed_in? && @member == current_member %>
            <%= form_with(model: @member,  id:'avatar-form') do |f| %>
              <%= f.file_field(:profile_image, direct_upload: true, accept: 'image/*', class: "sr-only", data:{action:'change->avatar#cropAvatar',target:'avatar.source'}) %>
              <%# f.submit "Update", class: "btn btn-primary" %>
            <% end %>
          <% end %>
        </label>
      </div>
      <h4 class="mt-4"><%= @member.first_name %></h4>
      <p class="mb-2 text-muted small"><%= @member.email %></p>
      <% if signed_in? && @member == current_member %>
        <div class="dropdown">
          <a class="btn btn-info btn-sm dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Edit Menu
          </a>
          <div class="dropdown-menu" >
            <%= link_to("Change Password", edit_password_members_path, class:"dropdown-item" ) %>
            <%= link_to('Delete Photo', delete_profile_photo_members_path, method: :patch, class:"dropdown-item") if current_member.profile_image.attached? %>
            <%= link_to("Edit Profile", edit_member_registration_path,class:"dropdown-item") %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_search-form.html.erb
<%= form_with(url: search_path, class: "bg-light shadow-sm p-3 rounded", local: true, method: :get) do |f| %>
  <div class=" input-group input-group-lg">
    <%= f.text_field :search, class: 'form-control', placeholder: 'Search casting calls' %>
    <div class="input-group-append">
      <%= f.submit "Search", disable_with: 'Searching...', class:"btn btn-lg btn-outline-secondary" %>
    </div>
  </div>
<% end %>

app/views/layouts/_toasts.html.erb
<%# messages and alerts with bootsrap toast %>
<% unless flash.empty? %>
<% flash.each do |type, message| %>
<div aria-live="assertive" aria-atomic="true" style="">
  <div class="toast">

    <%# <div class="toast-header bg-<%= bootstrap_class_for(type) %>
      <%# <img src="..." class="rounded mr-2" alt="..."> %>
      <%# <strong class="mr-auto text-uppercase ml-2"> %>
        <%# <%= type %>
      <%# </strong> %>
      <%# <small>11 mins ago</small> %>
      <%# <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close"> %>
        <%# <span aria-hidden="true">&times;</span> %>
      <%# </button> %>
    <%# </div> %>

    <div class="toast-body rounded bg-<%= bootstrap_class_for(type) %>" data-dismiss="toast">
      <%= message %>
    </div>
  </div>
</div>
<% end %>
<% end %>

app/views/layouts/_usernav.html.erb
<% if member_signed_in? %>
  <ul class="nav navbar-nav navbar-right ">
    <li class="nav-item dropdown bg-gray-200 border border-gray-300 rounded">
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <%# image_tag(profile_img, :alt => "member", :size => "22", class: "member-menu-thumb") %>
        <span class="ml-2"><%= icon("person-circle", class: "text-info", width:"20px", height:"20px") %></span> <%= current_member.first_name %>
      </a>
      <div class="dropdown-menu dropdown-menu-right" style="min-width: 250px;">
        <p class="px-4 mb-0 text-muted">
          <span class="font-weight-bold text-uppercase small"><%= current_member.first_name %> <%= current_member.last_name %></span>
          <span class="small d-block"><%= current_member.email %></span>
        </p>
        <div class="dropdown-divider"></div>
        <%= link_to "Post New casting call", new_job_path, :class => "dropdown-item" %>
        <div class="dropdown-divider"></div>
        <%= link_to "Your account", member_path(current_member), :class => "dropdown-item" %>
        <div class="dropdown-divider"></div>
        <%= link_to "Log Out", destroy_member_session_path, method: :delete, :class => "dropdown-item" %>
      </div>
    </li>
  </ul>
<% else %>
  <ul class="nav navbar-nav">
    <li class='nav-item'><%= link_to "Log In", new_member_session_path, :class => "nav-link"%></li>
    <li class='nav-item'><%= link_to "Sign Up", new_member_registration_path, :class => "btn btn-outline-action " %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/navbar" %>
  <%= render "layouts/toasts" %> 
    <%= yield :jumbotron%>
    <div class="content">
      <%= yield %>
    </div>
     <%= render "layouts/footer" %>
     <%= render "layouts/modal" %>
  </body>
</html>