config/routes.rb
Rails.application.routes.draw do
  resources :jobs do
    member do
      put :publish
      put :unpublish
      put :apply
      patch :remove_attachment
    end
  end

  root to: "pages#home"
  get "/search", to: "jobs#search"
  get "/hello", to: "pages#hello"
  get "/goodbye", to: "pages#goodbye"
  devise_for :members, controllers: { omniauth_callbacks: "members/omniauth_callbacks", registrations: "members/registrations" }
  resources :members do
    collection do
      get :edit
      get :edit_password
      patch :update_password
      patch :delete_profile_photo
    end
  end
end

app/models/member.rb
# == Schema Information
#
# Table name: members
#
#  id                     :bigint           not null, primary key
#  admin                  :boolean          default(FALSE)
#  castr                  :boolean          default(FALSE)
#  confirmation_sent_at   :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :inet
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string
#  last_name              :string
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :inet
#  provider               :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  sign_in_count          :integer          default(0), not null
#  talent                 :boolean          default(FALSE)
#  uid                    :string
#  unconfirmed_email      :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_members_on_confirmation_token    (confirmation_token) UNIQUE
#  index_members_on_email                 (email) UNIQUE
#  index_members_on_reset_password_token  (reset_password_token) UNIQUE
#
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :trackable,
         :omniauthable, omniauth_providers: %i[facebook]

  has_one_attached :profile_image
  has_many :jobs, dependent: :destroy
  validate :acceptable_image

  ROLES = ["admin", "castr", "talent"]

  def acceptable_image
    return unless profile_image.attached?

    errors.add(:profile_image, "is nil") if profile_image.attached?.nil?
    errors.add(:profile_image, "is too big") unless profile_image.byte_size <= 1.megabyte
    acceptable_types = ["image/jpeg", "image/png"]
    errors.add(:profile_image, "must be JPEG or PNG") unless acceptable_types.include?(profile_image.content_type)
  end

  def avatar
    if profile_image.attached?
      return self.profile_image.variant(resize: "200x200!").processed
    else
      #render image placeholder
      print "<p>There is no image</p>"
    end
  end

  def self.from_omniauth(auth)
    member = find_or_initialize_by(provider: auth.provider, uid: auth.uid)
    member.email = auth.info.email
    member.password = Devise.friendly_token[0, 20]
    member.first_name = auth.info.name.split(" ").first
    member.last_name = auth.info.name.split(" ").last
    # member.profile_img = auth.info.image # assuming the member model has an image
    # If you are using confirmable and the provider(s) you use validate emails,
    # uncomment the line below to skip the confirmation emails.
    # user.skip_confirmation!
    member.save!
    member
  end

  # def password_required?
  #   new_record? || password.present? || password_confirmation.present?
  # end

  # Overwrite devise update without password method
  # def update_without_password(params)
  #   if provider.nil?
  #     params.delete(:current_password)
  #     #   if params[:password].blank?
  #     #     params.delete(:password)
  #     #     params.delete(:password_confirmation) if params[:password_confirmation].blank?
  #   end

  #   result = update_attributes(params)
  #   clean_up_passwords
  #   result
  # end
end

app/controllers/members/omniauth_callbacks_controller.rb
class Members::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # render :json => request.env["omniauth.auth"]
    @member = Member.from_omniauth(request.env["omniauth.auth"])
    if @member.persisted?
      sign_in_and_redirect @member, event: :authentication #this will throw if @member is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_member_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/members/registrations_controller.rb
class Members::RegistrationsController < Devise::RegistrationsController
  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def after_sign_up_path_for(_resource)
    root_path
  end

  def after_update_path_for(resource)
    member_path(@member)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_member!

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = current_member
  end

  def update
    @member = current_member
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to member_path(@member), notice: "Avatar Updated" }
        # format.js { flash.now[:notice] = "Avatar Updated" }
        #format.json { render json: @member.profile_image }
      else
        format.html { redirect_to member_path(@member), notice: "Avatar Did Not Update" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete_profile_photo
    @member = current_member
    current_member.profile_image.purge
    redirect_to member_path(@member), notice: "Photo Deleted"
  end

  def edit_password
    @member = current_member
  end

  def update_password
    @member = current_member
    if @member.update(member_params)
      # Sign in the member by passing validation in case their password changed
      bypass_sign_in(@member)
      redirect_to member_path(@member), notice: "Password successfully changed"
    else
      render "edit_password"
    end
  end

  private

  def member_params
    # NOTE: Using `strong_parameters` gem
    params.require(:member).permit(:password, :password_confirmation, :profile_image)
  end
end

app/views/members/_avatar.html.erb
<% if @member.avatar  %>
  <%= image_tag(@member.avatar ,class:"img-fluid border border-3 border-info rounded-circle", id:"avatar") %>
<% else %>
  <%= icon("person-circle",  width: 150, height: 150, class: "text-info align-middle", id:"avatar" ) %>
<% end %>

app/views/members/_member_jobs.html.erb
<% @member.jobs.each do |job| %>

<div class="card rounded shadow-sm p-3 mb-3 ">
<div>
  <p class="float-right">
    <% if job.published? %>
        <span data-toggle="tooltip" data-placement="top" title="Published" id='status', class='text-success'><%= icon('eye') %></span>
    <% else %>
      <span data-toggle="tooltip" data-placement="top" title="Pending" id='status', class='text-secondary'><%= icon('eye-slash') %></span>
    <% end %>
  </p>
  <div class="float-left">
    <% unless job.created_at < DateTime.current.days_ago(5) %>
      <span class="badge bg-action small text-dark mr-2">New</span>
    <% end %>
  </div>
  <h4><%= link_to job.title, job_path(job), remote: false, class:'text-reset', id:'remote' %></h4>
</div>

<p class="small text-secondary">Created on: <%= date(job.created_at) %></p>
<p class="font-weight-light"><%= truncate(job.description, :ommision => "... Read More", :length => 150) %></p>
<p class="text-muted small mb-0">Union Status: <%= job.union_status %></p>
<p class="text-muted small mb-0">Shoots: <%= job.shoot_start_date %> - <%= job.shoot_end_date %> in <%= job.shoot_location %></p>
<p class="font-weight-bold"><span class="text-muted small">Compensation:</span> $<%= job.payment %>/<%= job.pay_interval %></p>
  
<%# if signed_in? && author_of(job) || admin? %>
  <div class="d-inline">
    <div class="btn-group">
        <div class="btn-group" role="group" aria-label="Basic outlined example">
          <% if can? :update, job %>
            <%= link_to('Edit', edit_job_path(job),class:"btn btn-sm btn-outline-secondary" )%>
          <% end %>

          <% if can? :destroy, job %>
            <%= link_to 'Delete', job_path(job), class:"btn btn-sm btn-outline-secondary", method: :delete, data: { confirm: "Are you sure?" }  %>
          <% end %>
        </div>
    </div>
  </div>
<%# end %>
</div>

<% end %>

app/views/members/edit.html.erb
<div class="container mt-5" style="max-width: 600px;">
  <div class="row justify-content-center">
    <div class="col">
      <div class="bg-light shadow-sm rounded p-3">
        <h4>Edit Profile</h4>
        <%= form_for(@member, as: :member) do |f| %>
          <%= render "devise/shared/error_messages", resource: @member %>
          <div class="form-group input-group-lg">
            <%= f.label :first_name %><br />
            <%= f.text_field :first_name, autofocus: true, autocomplete: "Name", class: 'form-control' %>
          </div>
          <div class="form-group input-group-lg">
            <%= f.label :last_name %><br />
            <%= f.text_field :last_name, autofocus: true, autocomplete: "Lastname", class: 'form-control'  %>
          </div>
          <div class="form-group input-group-lg">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control'  %>
          </div>
          <%# if devise_mapping.confirmable? && @member.pending_reconfirmation? %>
          <div>Currently waiting confirmation for: <%# @member.unconfirmed_email %></div>
          <%# end %>
          <div class="form-group input-group-lg">
            <div class="actions">
              <%= f.submit "Update", class: "btn btn-primary btn-lg" %>
            </div>
          </div>
        <% end %>
        <hr/>
        <h5>Delete my account</h5>
        <p>Once deleted, your account is gone forever.<%= button_to "Delete your account", registration_path(@member), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-outline-danger" %></p>
      </div>
    </div>
  </div>
</div>

app/views/members/edit_password.html.erb
<%= render "layouts/profile_header" %>
<div class="container mt-5" style="max-width: 600px;">
  <div class="row justify-content-center">
    <div class="col">
      <div class="bg-light shadow-sm rounded p-3">
        <h4>Change Password</h4>
        <%= form_for(@member, :url => { :action => "update_password" } ) do |f| %>
          <%= render "devise/shared/error_messages", resource: @member %>
          <div class="form-group input-group-lg">
            <%= f.label :password %>
            <span class="small text-warning">
              <% if @minimum_password_length %>
                ( <%= @minimum_password_length %> characters minimum )
              <% end %></span>
            <%= f.password_field :password, autocomplete: false, class: 'form-control'  %>
            <small id="emailHelp" class="form-text text-muted"> 6 characters minimum</small>
          </div>
          <div class="form-group input-group-lg">
            <%= f.label :password_confirmation %><br />
            <%= f.password_field :password_confirmation, autocomplete: false, class: 'form-control'  %>
          </div>
          <div class="form-group input-group-lg">
            <div class="actions">
              <%= f.submit "Update", class: "btn btn-primary btn-lg" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>
</div>

app/views/members/show.html.erb
<%= render "layouts/profile_header" %>

<div class="container mt-5">
  <div class="row justify-content-center">    
    <div class="col-lg-6">
      <div class="">
        <% if @member.jobs.any? %>
          <div class=" mb-3 rounded clearfix bg-light p-2">
          <% if @member == current_member %>
          <h5 class="p-2 m-0 float-left">Your Casting Calls</h5>
          <% else %>
          <h5 class="p-2 m-0 float-left"><%= @member.first_name %>'s Casting Calls</h5>
          <% end %> 
          </div>
          <%= render "member_jobs" %>
        <% else %>
          <div class="text-center d-flex justify-content-center flex-column align-items-center h-100">
          <p>You have not posted any casting calls yet</p>
          <%= link_to "Create New Casting Call", new_job_path, class:"btn btn-action float-right" %>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/members/update.js.erb
var avatar = document.querySelector('.avatar');
avatar.innerHTML = "<%= j render partial: 'avatar' %>";